# Generated by Django 3.2.3 on 2024-02-05 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20240205_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='shop_it',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoppers', to='recipes.recipe'),
        ),
    ]
