# Generated by Django 3.2.3 on 2024-01-31 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240201_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=144, unique=True, verbose_name='Адрес почты'),
        ),
    ]
